### ISSUE TITLE
Error in the evaluation process

### ISSUE THREAD

**Issue by jorgemn9** [ssuralcmu/ContextualFusion#2]
Hello! First of all, thanks for your great work. Now I am training the LiDAR+Camera using mmdet3d and your dataset "AdverseOp3D", but when the first epoch finishes and the evaluation process starts, I get the following error:

assert set(self.pred_boxes.sample_tokens) == set(self.gt_boxes.sample_tokens), \
AssertionError: Samples in split doesn't match samples in predictions.

Do you any clue on how to solve this?

Thanks in advance.

**Comment by ssuralcmu** [comment]
Hi jorgemn9,

You should have a file- [python installation]/site-packages/nuscenes/utils/splits.py which defines the NuScenes splits. Removing the assertion from there should fix the problem. This happens because we use our custom dataset in the NuScenes format and this does not have match the general expectations of the number of scenes for train and val from NuScenes.

Best,
Shounak

**Comment by jorgemn9** [comment]
Hi @ssuralcmu,

Thank you very much for your answer. But I still have a question related with the file splits.py. I have seen that in your repository you have edited the scenes of train_detect, vals and test of splits.py. However, I have checked if these scenes appear in the file scene.json of "v1.0-trainval" and "v1.0-test" of AdverseOP3D dataset and they don't appear, except "scene-0077" from test. Do you know anything about this?

Thanks in advance,
Jorge

**Comment by ssuralcmu** [comment]
Hi,

For the AdverseOp3D dataset, to make it compatible with the NuScenes library, we use a dummy scene number. For say night-time NuScenes, another specific subset is used. 
If you face further issues, you can modify the splits.py file to ensure that only the required scene- scene-0077 in this case, is defined.

Best,
Shounak

**Comment by ssuralcmu** [comment]
The config file for ContextualFusion is at configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml. This is also outlined in the run command in the top-level readme. 

This uses our convolutional gating module. Some parameters are inherited from top level yaml files based on the original BEVFusion repository.
